name: CCflow bulid
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
    - name: dotnet env construction
      run: |
        apt-get update
        apt-get install -y wget
        wget https://packages.microsoft.com/config/ubuntu/20.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        dpkg -i packages-microsoft-prod.deb
        rm packages-microsoft-prod.deb
        apt-get install -y apt-transport-https
        apt-get install -y dotnet-sdk-3.1
        mkdir -p /root/.nuget/packages
    - name: ccflow build
      run: |
        cp /home/runner/work/ccflow/ccflow/packages/pdflib_dotnet /root/.nuget/packages
        rm -fr /home/runner/work/ccflow/ccflow/CCFlow/bin
        rm -fr /home/runner/work/ccflow/ccflow/CCFlow/obj
        dotnet build /home/runner/work/ccflow/ccflow/CCFlow/CCFlow.NetCore.csproj
        ls /home/runner/work/ccflow/ccflow/CCFlow/bin/Debug/netcoreapp3.1
